### ISSUE TITLE
Behat failing

### ISSUE THREAD

**Issue by ewallah** [moodlehq/moodle-availability_mobileapp#1]
001 Scenario: Test condition
# availability/condition/mobileapp/tests/behat/availability_mobileapp.feature:29
      And I set the following administration settings values:
# availability/condition/mobileapp/tests/behat/availability_mobileapp.feature:20
       Xpath matching locator "//*[label[contains(., 'Enable conditional access')]|span[contains(., 'Enable conditional access')]]/ancestor::div[contains(concat(' ', normalize-space(@class), ' '), ' form-item ')]/descendant::div[contains(concat(' ', @class, ' '), ' form-group ')]/descendant::*[self::input | self::textarea | self::select][not(./@type = 'submit' or ./@type = 'image' or ./@type = 'hidden')]" not found. (Behat\Mink\Exception\ElementNotFoundException)

Moodle 3.2.2+ (Build: 20170324)
Php: 7.1.3.2.1, mysqli: 5.7.17-0ubuntu0.16.04.1, OS: Linux 4.4.0-67-generic x86_64
Server OS "Linux", Browser: "firefox"

![availability_mobileapp_i-set-the-following-administration-settings-values-_20](https://cloud.githubusercontent.com/assets/1324161/24333924/36f910ae-1261-11e7-88df-0ad9d0d2ac6a.png)

**Comment by ewallah** [comment]
Got the behat testing working in Moodle 3.2 with this background:

>   Background:
    Given the following "courses" exist:
      | fullname | shortname | format | enablecompletion |
      | Course 1 | C1        | topics | 1                |
    And the following "users" exist:
      | username |
      | teacher1 |
      | student1 |
    And the following "course enrolments" exist:
      | user     | course | role           |
      | teacher1 | C1     | editingteacher |
      | student1 | C1     | student        |
    And the following config values are set as admin:
      | enableavailability     | 1 |
      | enablewebservices      | 1 |
      | enablemobilewebservice | 1 |
    And I log in as "admin"
    And I navigate to "Mobile settings" node in "Site administration > Mobile app"
    And I click on "Enable web services for mobile devices" "checkbox"
    And I click on "Save changes" "button"
    And I log out

**Comment by jleyva** [comment]
Hi,
thanks for the fix, would you like to create a pull request to integrate a commit keeping your authorship?

**Comment by ewallah** [comment]
Hi,

Since my report on March 26, we also have MDL-56614. So I implemented some other changes.
Give me some time to create a pull request..

R
