### ISSUE TITLE
Php fatal error when running phpunit tests

### ISSUE THREAD

**Issue by ewallah** [moodlehq/moodle-availability_mobileapp#8]
PHP Fatal error:  Declaration of availability_mobileapp_condition_testcase::setUp() must be compatible with PHPUnit\Framework\TestCase::setUp(): void in availability/condition/mobileapp/tests/condition_test.php on line 42

**Comment by michael-milette** [comment]
This is a compatibility issue first introduced in Moodle 3.10.

**Comment by jleyva** [comment]
Thanks, I integrated the changed and follow the advise regarding the branching for 3.10
